version: '3.7'

services:
  http-proxy:
    build:
      context: box/nginx
    restart: unless-stopped
    depends_on:
      - app
      - docs
    ports:
      - "80:80"

  app:
    build:
      context: .
      target: dev
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - COMPOSER_CACHE_DIR=/app/var/composer
    env_file:
      - .env

  docs:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/base.openapi.yml:/app/base.openapi.yml
    environment:
      - LAYOUT=BaseLayout
      - SWAGGER_JSON=/app/base.openapi.yml
